security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # utilisé pour recharger l'utilisateur depuis la session
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            # On laisse les outils de dev (profiler, css, images) accessibles sans sécurité
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AppAuthenticator

            logout:
                path: app_logout
                # On redirige vers l'accueil après la déconnexion
                target: app_home

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                # Par défaut, activé par une checkbox dans le formulaire de login
                # always_remember_me: true

    # Contrôle d'accès : définit qui peut voir quoi
    access_control:
        # 1. On autorise l'accès PUBLIC à la page de connexion
        - { path: ^/login, roles: PUBLIC_ACCESS }

        # 2. TOUT le reste du site (^) nécessite d'être connecté (ROLE_USER)
        - { path: ^/, roles: ROLE_USER }

# Configuration spécifique pour les tests
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Valeur minimale pour la performance des tests
                time_cost: 3
                memory_cost: 10
